name: iosApp
options:
  bundleIdPrefix: com.webrtckmp
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15"

targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: iosApp
        excludes:
          - "**/*.md"
    info:
      path: iosApp/Info.plist
    settings:
      base:
        SWIFT_VERSION: "5.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.webrtckmp
        INFOPLIST_FILE: iosApp/Info.plist
        ENABLE_BITCODE: NO
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
