import SwiftUI
import ComposeApp

struct ContentView: View {
    // iOS has no "context" — we pass an empty PlatformContext
    private let viewModel = CallViewModel(context: PlatformContext(), serverUrl: "ws://localhost:3000")

    var body: some View {
        ComposeView(viewModel: viewModel)
            .ignoresSafeArea(.all)
    }
}

// Bridges the KMP Compose UI into SwiftUI
struct ComposeView: UIViewControllerRepresentable {
    let viewModel: CallViewModel

    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewControllerKt is generated by KMP — it calls the App() composable
        MainViewControllerKt.MainViewController(viewModel: viewModel)
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
