import SwiftUI
import ComposeApp

struct ContentView: View {
    // @State keeps the ViewModel alive across SwiftUI view re-creations.
    // A plain `let` here would build a new CallViewModel every time SwiftUI
    // re-runs the body, leaking CoroutineScopes and stacking WebRTC state.
    @State private var viewModel = CallViewModel(
        context: PlatformContext(),
        serverUrl: "ws://localhost:3000",
    )

    var body: some View {
        ComposeView(viewModel: viewModel)
            .ignoresSafeArea(.all)
    }
}

// Bridges the KMP Compose UI into SwiftUI
struct ComposeView: UIViewControllerRepresentable {
    let viewModel: CallViewModel

    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewControllerKt is generated by KMP — it calls the App() composable
        MainViewControllerKt.MainViewController(viewModel: viewModel)
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
